name: desbordante

services:
  postgres:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:5672"

  backend:
    image: ghcr.io/desbordante/desbordante-server:${BACKEND_IMAGE_TAG}
    volumes:
      - ./volumes/uploads:${UPLOADED_FILES_DIR_PATH}
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
    restart: always
    ports:
      - "${BACKEND_PORT}:8000"

  celery:
    image: ghcr.io/desbordante/desbordante-server:${BACKEND_IMAGE_TAG}
    command: /celery
    volumes:
      - ./volumes/uploads:${UPLOADED_FILES_DIR_PATH}
    env_file:
      - .env
    depends_on:
      - rabbitmq
    restart: always

  flower:
    image: ghcr.io/desbordante/desbordante-server:${BACKEND_IMAGE_TAG}
    command: /flower
    volumes:
      - ./volumes/uploads:${UPLOADED_FILES_DIR_PATH}
    env_file:
      - .env
    environment:
      - FLOWER_USER=admin
      - FLOWER_PASSWORD=admin
    depends_on:
      - rabbitmq
      - celery
    restart: always
    ports:
      - "5555:5555"

volumes:
  postgres_data:
  rabbitmq_data:
