apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: GitHub
      prefix: ghcr.io
      api_url: https://ghcr.io
    #   credentials: pullsecret:argocd/regcred
      default: true
