apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}-service
spec:
  selector:
    project: {{ .Release.Name }}    # Selecting PODS with those Labels
  ports:
  {{- range $host, $port := default (dict .Values.host .Values.port) .Values.hosts }}
    - name: {{ $port }}-port
      port: {{ $port }}  # Port on Load Balancer
      targetPort: {{ $port }}  # Port on POD
  {{- end }}
  type: ClusterIP
