name: Pull the git repository on the server
on:
  push:
    branches:
      - main
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
    - name: Pull the git repository with ssh
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: git --work-tree=$WORK_TREE --git-dir=$GIT_DIR pull
      env:
        WORK_TREE: ${{ vars.PROJECT_DIR }}
        GIT_DIR: ${{ vars.PROJECT_DIR }}/.git