name: Pull the git repository on the server
on:
  push:
    branches:
      - main
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
    - name: Pull the git repository with ssh
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: \
          if [ -d ${{ vars.PROJECT_DIR }}/.git ]; \
          then git -C ${{ vars.PROJECT_DIR }} pull; \
          else git clone ${{ github.server_url }}/${{ github.repository }} ${{ vars.PROJECT_DIR }}; \
          fi