name: Pull the git repository on the server
on:
  push:
    branches:
      - main
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
    - name: Pull the git repository with ssh
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: git -C ${{ vars.PROJECT_DIR }} pull origin main